### ISSUE TITLE
Offer to help: add some structure to ToC of project page

### ISSUE THREAD

**Issue by claremacrae** [SimonCropp/MarkdownSnippets#259]
Hi Simon,

As the number of features has increased, I have started to struggle to see what I'm looking for in the long table of contents on the main page...

I realise that this is a nice problem to have (lots of features!) - but if you would like a PR to have a stab at adding some grouping sections, I would be happy to do this...

**Comment by claremacrae** [comment]
![image](https://user-images.githubusercontent.com/4840096/87671612-8aa84b00-c769-11ea-9c26-b752da8dd26a.png)

**Comment by SimonCropp** [comment]
this should be cleaned up now

**Comment by claremacrae** [comment]
Thanks Simon. I wanted to have a go at creating a PR to show you the kind of thing I had in mind, as it's easier than trying to describe it in words...

How do I now run mdsnippets on this project, or what am I doing wrong here:

```bash
# cd [my fork]
#  update my fork to your latest (on master)
dotnet tool update --global MarkdownSnippets.Tool
# Gives Tool 'markdownsnippets.tool' was reinstalled with the latest stable version (version '19.0.1').
mdsnippets
```

Gives this output (macOS 10.15.5):

```
Config:
    RootDir: /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae
    ReadOnly: False
    WriteHeader: True
    Header: 
    UrlPrefix: 
    LinkFormat: GitHub
    TocLevel: 1
    MaxWidth: 80
    ValidateContent: True
    FileConfigPath: /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/src/mdsnippets.json (exists:True)
    TocExcludes:
        Credits
        Release Notes
        Icon
Added 21 .source.md files
Searching 253 files for snippets
Added 34 snippets
Unhandled exception. System.Exception: Duplicate include: file
   at MarkdownSnippets.IncludeFinder.ReadIncludes(String[] directories) in C:\projects\markdownsnippets\src\MarkdownSnippets\Reading\IncludeFinder.cs:line 27
   at MarkdownSnippets.DirectoryMarkdownProcessor.AddIncludeFilesFrom(String directory) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 139
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, Boolean scanForMdFiles, Boolean scanForSnippets, Boolean scanForIncludes, Action`1 log, AppendSnippetGroupToMarkdown appendSnippetGroup, Boolean writeHeader, String header, DirectoryFilter directoryFilter, Boolean readOnly, LinkFormat linkFormat, Int32 tocLevel, IEnumerable`1 tocExcludes, Boolean treatMissingSnippetAsWarning, Boolean treatMissingIncludeAsWarning, Int32 maxWidth, String urlPrefix, Boolean validateContent) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 83
   at Program.Inner(String targetDirectory, ConfigInput configInput) in C:\projects\markdownsnippets\src\MarkdownSnippets.Tool\Program.cs:line 29
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at Program.Main(String[] args) in C:\projects\markdownsnippets\src\MarkdownSnippets.Tool\Program.cs:line 12
   at Program.<Main>(String[] args)
[1]    82304 abort      mdsnippets
```

**Comment by claremacrae** [comment]
Searching for .include.md in the whole project I see multiple `file.include.md` so that's obviously the problem... So I'm puzzled as to why you don't see the same thing:

![image](https://user-images.githubusercontent.com/4840096/88258562-55937f80-ccb8-11ea-93de-8529a8bd353d.png)

**Comment by claremacrae** [comment]
So I renamed a couple of those .file.md files out of the way and it gets further, to:

```
...
Added 0 files for snippets
Added 0 snippets
Processing /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/readme.source.md
Processing /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/docs/mdsource/indentation.source.md
Processing /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/docs/mdsource/snippet-exclusion.source.md
Processing /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/docs/mdsource/msbuild.source.md
Processing /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/docs/mdsource/api.source.md
Failed: Cannot access when IsInError. Key: readingfilessimple. FileLocation: /Users/clare/Documents/develop/Markdown/MarkdownSnippets-claremacrae/src/Tests/Snippets/Usage.cs(10-10). Error: Line too long: var files = Directory.EnumerateFiles(@"C:\path", "*.cs", SearchOption.AllDirectories);
```

**Comment by claremacrae** [comment]
I can get it to run to completion if I make these changes to `src/mdsnippets.json`:

```diff
diff --git a/src/mdsnippets.json b/src/mdsnippets.json
index 30aed88..54950cc 100644
--- a/src/mdsnippets.json
+++ b/src/mdsnippets.json
@@ -1,6 +1,6 @@
 ﻿{
   "TocLevel": 1,
   "TocExcludes": [ "Credits", "Release Notes", "Icon" ],
-  "MaxWidth": 80,
-  "ValidateContent": true
+  "TreatMissingSnippetAsWarning": true,
+  "TreatMissingIncludeAsWarning": true
 }
```

**Comment by claremacrae** [comment]
(The previous renaming of duplicate `file.include.md` files is still required)
