### ISSUE TITLE
MarkdownSnippets.SnippetException: WriteHeader is not allowed with InPlaceOverwrite convention.

### ISSUE THREAD

**Issue by CaptainDredge** [SimonCropp/MarkdownSnippets#297]
#### Describe the bug

I think its less of a bug but more of an error on my part which I can't figure out. Pardon me but I've just started learning C# and .NET
I've installed [markdown snippet nuget package](https://nuget.org/packages/MarkdownSnippets.MsBuild/) to my `test` project. My code snippets are in `src` project and all my markdown files are in `doc` project. I've included the suggested [config.json file](https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/config-file.md) in `test` project where I installed the nuget package but I'm getting the following error when I build test:

```
Error		MarkdownSnippets: MarkdownSnippets.SnippetException: WriteHeader is not allowed with InPlaceOverwrite convention.
   at MarkdownSnippets.MarkdownProcessor..ctor(DocumentConvention convention, IReadOnlyDictionary`2 snippets, IReadOnlyList`1 includes, AppendSnippetsToMarkdown appendSnippets, IReadOnlyList`1 snippetSourceFiles, Int32 tocLevel, Boolean writeHeader, String rootDirectory, Boolean validateContent, String header, IEnumerable`1 tocExcludes) in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\MarkdownProcessor.cs:line 57
   at MarkdownSnippets.DirectoryMarkdownProcessor.Run() in C:\projects\markdownsnippets\src\MarkdownSnippets\Processing\DirectoryMarkdownProcessor.cs:line 195
   at MarkdownSnippets.DocoTask.Execute() in C:\projects\markdownsnippets\src\MarkdownSnippets.MsBuild\DocoTask.cs:line 92	tests	C:\Users\prasharma\.nuget\packages\markdownsnippets.msbuild\21.0.1\build\MarkdownSnippets.MsBuild.targets	18	
```

Also, when I try to invoke it through dotnet-cli it gives the following error:

```
Failed: WriteHeader is not allowed with InPlaceOverwrite convention.
```

Any help will be highly appreciated 😄

**Comment by SimonCropp** [comment]
sorry. the docs here were wrong https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/config-file.md i have updated it.

try with 

```
{
  "Convention": "InPlaceOverwrite"
}
```

**Comment by SimonCropp** [comment]
is the project OSS? got a URL?

**Comment by CaptainDredge** [comment]
Thanks Simon. It worked for me when I removed `"WriteHeader": true,` . I guess these two cannot be together in config `"WriteHeader": true,` and `"WriteHeader": true,`

**Comment by SimonCropp** [comment]
good to hear
