### ISSUE TITLE
MarkdownSnippets.MSBuild crashes with file access exception if you use the /bl parameter with dotnet build

### ISSUE THREAD

**Issue by jnm2** [SimonCropp/MarkdownSnippets#370]
If you use the `/bl:mylog.binlog` parameter with `dotnet build`, MarkdownSnippets.MSBuild seems to try to open the binlog with `File.OpenText`:

```
markdownsnippets.msbuild\22.0.3\build\MarkdownSnippets.MsBuild.targets(18,5): error MSB4018: The
"MarkdownSnippets.DocoTask" task failed unexpectedly.

System.IO.IOException: The process cannot access the file 'C:\Users\Joseph\Source\Repos\shouldly\artifacts\Logs\build.binlog'
because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at MarkdownSnippets.FileSnippetExtractor.Read(String path, Int32 maxWidth, String newLine) in /_/src/MarkdownSnippets/Reading/FileSnippetExtractor.cs:line 102
   at MarkdownSnippets.FileSnippetExtractor.<>c__DisplayClass7_0.<Read>b__1(String path) in /_/src/MarkdownSnippets/Reading/FileSnippetExtractor.cs:line 83
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, AppendSnippetsToMarkdown appendSnippets, ShouldIncludeDirectory shouldIncludeDirectory, DocumentConvention convention, Boolean scanForMdFiles, Boolean scanForSnippets, Boolean scanForIncludes, Action`1 log, Nullable`1 writeHeader, String header, Nullable`1 readOnly, Int32 tocLevel, IEnumerable`1 tocExcludes, Boolean treatMissingAsWarning, Int32 maxWidth, Boolean validateContent, String newLine) in /_/src/MarkdownSnippets/Processing/DirectoryMarkdownProcessor.cs:line 126
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, ShouldIncludeDirectory shouldIncludeDirectory, DocumentConvention convention, Boolean scanForMdFiles, Boolean scanForSnippets, Boolean scanForIncludes, Action`1 log, Nullable`1 writeHeader, String header, Nullable`1 readOnly, LinkFormat linkFormat, Int32 tocLevel, IEnumerable`1 tocExcludes, Boolean treatMissingAsWarning, Int32 maxWidth, String urlPrefix, Boolean validateContent, String newLine, Boolean hashSnippetAnchors) in /_/src/MarkdownSnippets/Processing/DirectoryMarkdownProcessor.cs:line 51
   at MarkdownSnippets.DocoTask.Execute() in /_/src/MarkdownSnippets.MsBuild/DocoTask.cs:line 58
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

Is this user error or a problem with MarkdownSnippets?

#### Minimal Repro

Create this .csproj file anywhere. In the same directory, run `git init .` to make MarkdownSnippets happy, then run `dotnet build /bl:build.binlog` to repro the crash.

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MarkdownSnippets.MsBuild" Version="23.1.0" PrivateAssets="all" />
  </ItemGroup>

</Project>
```

#### Submit a PR that fixes the bug

Happy to do this, but I will need design direction at least. Looking at your source code now.

**Comment by jnm2** [comment]
Looks like the problem might be that MarkdownSnippets assumes it can open all files recursively in the current directory no matter what kind they are or whether they are in use:

https://github.com/SimonCropp/MarkdownSnippets/blob/c4253babb99033d7508928c5d2f3c2442da04602/src/MarkdownSnippets/Reading/FileFinder.cs#L32-L42

There could also be other kinds of IO issues.

Is the fix to add recovery and simply ignore unopenable files? Or to be smarter about what kinds of files are being read, e.g., why is it trying to read a binary file?

**Comment by jnm2** [comment]
Ooh, this might be smart. In line with `https://github.com/SimonCropp/MarkdownSnippets/blob/master/docs/exclusion.md#ignored-paths`, can we add `.bin*` to the default excluded file extensions and maybe ignore directories named `artifacts` and `logs`? That would make the out-of-the-box defaults nice.

Then on top of that, some kind of graceful recovery in case the scanning finds a file that is in use by another process?

**Comment by jnm2** [comment]
I'm trying to figure out a simple workaround. I noticed that DocoTask has an ExcludeDirs parameter, which seems perfect:

https://github.com/SimonCropp/MarkdownSnippets/blob/c4253babb99033d7508928c5d2f3c2442da04602/src/MarkdownSnippets.MsBuild/DocoTask.cs#L23

But it is unused:

https://github.com/SimonCropp/MarkdownSnippets/blob/c4253babb99033d7508928c5d2f3c2442da04602/src/MarkdownSnippets.MsBuild/MarkdownSnippets.MsBuild.targets#L18-L21

Would you be open to passing `ExcludeDirs="$(MarkdownSnippetsExcludeDirs)"` in the .targets so that this can be a one-liner in the .csproj file?

**Comment by jnm2** [comment]
I think there is no current workaround besides just going without binlogs in CI. I tried every combination of settings in `src/mdsnippets.json` (existing file) and `mdsnippets.json` (next to where the `artifacts` directory actually is) that I could think of.

**Comment by SimonCropp** [comment]
i think binlog should be ignored by default. but should also ignore locked files. 

if that works for u i will release a new version with those changes

**Comment by jnm2** [comment]
Works for me. I had suggested ignoring `.bin*`, not just `.binlog`, what do you think?

**Comment by SimonCropp** [comment]
> I had suggested ignoring .bin*

how confident r we there are no text files with the bin prefix?

ok i deployed 23.1.1 with binlog excluded to get u unstuck. ignoreing locked files will take a little more effort

**Comment by jnm2** [comment]
Fair point, `.bin` was the only other file extension that came to mind besides `binlog`.

Thank you very much! Removed the workaround in Shouldly.

**Comment by SimonCropp** [comment]
bin is already ignored

i didnt want to silently ignore locked files, since it would make it difficult to debug a missing snippet when a file is locked. and i dont have logging in that scope to surface it. yet
