### ISSUE TITLE
Global tool throws ArgumentOutOfRangeException if . is used as the directory argument

### ISSUE THREAD

**Issue by martincostello** [SimonCropp/MarkdownSnippets#393]
#### Describe the bug

If `.` is used as the argument to `mdsnippets` as shorthand for the current directory, the tool prints an exception stack trace to the console.

```powershell
C:\Coding\justeat\httpclient-interception [Fix-Docs ≡]> mdsnippets .
Config:
    TargetDirectory: .
    UrlPrefix:
    LinkFormat: GitHub
    Convention: InPlaceOverwrite
    TocLevel: 2
    ValidateContent: False
    HashSnippetAnchors: False
    TreatMissingAsWarning: False
    FileConfigPath: .\mdsnippets.json (exists:True)
Found 105 files for snippets
Added 3 snippets (180ms)
Finished 251ms
Unhandled exception. System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at MarkdownSnippets.DirectoryMarkdownProcessor.ProcessFile(String sourceFile, MarkdownProcessor markdownProcessor) in /_/src/MarkdownSnippets/Processing/DirectoryMarkdownProcessor.cs:line 273
   at MarkdownSnippets.DirectoryMarkdownProcessor.Run() in /_/src/MarkdownSnippets/Processing/DirectoryMarkdownProcessor.cs:line 251
   at <Program>$.<<<Main>$>g__Inner|0_0>d.MoveNext() in /_/src/MarkdownSnippets.Tool/Program.cs:line 69
--- End of stack trace from previous location ---
   at <Program>$.<<Main>$>d__0.MoveNext() in /_/src/MarkdownSnippets.Tool/Program.cs:line 11
--- End of stack trace from previous location ---
   at <Program>$.<Main>(String[] args)
```

Instead the tool should expand the path as appropriate and process the files in the same way as if the fully qualified path to the directory had been specified instead without throwing an exception.

##### Tool version:

```powershell
C:\Coding\justeat\httpclient-interception [Fix-Docs ≡]> mdsnippets --version
mdsnippets 23.1.2+9aba99bdf0bddfcacbc35bba2c25bb4fe0458fd3
Finished 33ms
```

##### .NET SDK version

```powershell
C:\Coding\justeat\httpclient-interception [Fix-Docs ≡]> dotnet --version
5.0.203
```

#### Minimal Repro

Open a directory configured to use MarkdownSnippets in a terminal and run the following command:

```powershell
mdsnippets .
```

#### Submit a PR that fixes the bug

N/A

**Comment by SimonCropp** [comment]
can u try 23.1.3

**Comment by martincostello** [comment]
Yep, that fixes it 👍 

```powershell
C:\Coding\justeat\httpclient-interception [main ≡]> mdsnippets .
Config:
    TargetDirectory: C:\Coding\justeat\httpclient-interception
    UrlPrefix:
    LinkFormat: GitHub
    Convention: InPlaceOverwrite
    TocLevel: 2
    ValidateContent: False
    HashSnippetAnchors: False
    TreatMissingAsWarning: False
    FileConfigPath: C:\Coding\justeat\httpclient-interception\mdsnippets.json (exists:True)
Found 119 files for snippets
Added 3 snippets (185ms)
MarkdownProcessor Finished. 17ms
Finished 269ms
C:\Coding\justeat\httpclient-interception [main ≡]> mdsnippets --version
mdsnippets 23.1.3+7938b5074fc434024f8319f47fee8d2d03ff95b9
Finished 32ms
```
