### ISSUE TITLE
MarkdownSnippets.DocoTask fails with "cannot access file"

### ISSUE THREAD

**Issue by distantcam** [SimonCropp/MarkdownSnippets#684]
I'm getting an intermittent error during building in Visual Studio. I can fix the issue briefly by deleting the `.vs` folder, but after a bit it comes back.

Keeps happening to me for this repo https://github.com/distantcam/AutoCtor. The test project is where I reference [MarkdownSnippets.MsBuild 26.0.0](https://www.nuget.org/packages/MarkdownSnippets.MsBuild/26.0.0)

`markdownsnippets.msbuild\26.0.0\build\MarkdownSnippets.MsBuild.targets(18,5): error MSB4018`

```
System.IO.IOException: The process cannot access the file 'C:\src\auto\AutoCtor\.vs\AutoCtor\FileContentIndex\b055c019-ed76-4e27-8350-c427df144c65.vsidx' because it is being used by another process.
The "MarkdownSnippets.DocoTask" task failed unexpectedly.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at MarkdownSnippets.FileSnippetExtractor.Read(String path, Int32 maxWidth, String newLine) in /_/src/MarkdownSnippets/Reading/FileSnippetExtractor.cs:line 104
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MarkdownSnippets.DirectoryMarkdownProcessor..ctor(String targetDirectory, AppendSnippetsToMarkdown appendSnippets, ShouldIncludeDirectory directoryIncludes, ShouldIncludeDirectory markdownDirectoryIncludes, ShouldIncludeDirectory snippetDirectoryIncludes, DocumentConvention convention, Boolean scanForMdFiles, Boolean scanForSnippets, Boolean scanForIncludes, Action`1 log, Nullable`1 writeHeader, String header, Nullable`1 readOnly, Int32 tocLevel, IEnumerable`1 tocExcludes, Boolean treatMissingAsWarning, Int32 maxWidth, Boolean validateContent, String newLine) in /_/src/MarkdownSnippets/Processing/DirectoryMarkdownProcessor.cs:line 124
   at MarkdownSnippets.DocoTask.Execute() in /_/src/MarkdownSnippets.MsBuild/DocoTask.cs:line 59
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```
<details>
<summary>Visual Studio Version 17.8.3 Info</summary>
Microsoft Visual Studio Professional 2022
Version 17.8.3
VisualStudio.17.Release/17.8.3+34330.188
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Professional

Visual C++ 2022   00476-80000-00000-AA216
Microsoft Visual C++ 2022

ASP.NET and Web Tools   17.8.358.6298
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.8.358.6298
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.8.358.6298
Azure Functions and Web Jobs Tools

C# Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CodeRush for Roslyn   23.2.3.0
DevExpress CodeRush for Roslyn package.

CodeRush for Roslyn Tool Windows   23.2.3.0
DevExpress CodeRush for Roslyn Tool Windows package.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Extensibility Message Bus   1.4.39 (main@e8108eb)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

IndentRainbowPackage Extension   1.0
IndentRainbowPackage Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.8.17 (957fbed)
Support for debugging Mono processes with Visual Studio.

NuGet Package Manager   6.8.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.8.3.2358002+8c7fb27bf8e8d4f9ff8080b624b35bca5e812e97
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.8.119.0
Microsoft SQL Server Data Tools

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

Tweaks 2022   1.1.143
A collection of minor fixes and tweaks for Visual Studio to reduce the paper cuts and make you a happier developer

TypeScript Tools   17.0.20920.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.8.0-7.23572.1+7b75981cf3bd520b86ec4ed00ec156c8bc48e4eb
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.8.0-beta.23475.2+10f956e631a1efc0f7f5e49c626c494cd32b1f50
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSColorOutput64   2023.4
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Xamarin   17.8.0.156 (d17-8@bd02f18)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.8.3.6 (remotes/origin/d17-8@eccf46a291)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.8.16 (830b56a)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.2.2.0 (d17-5/45b0e14)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: d9a6e87
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@ca1552d

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.23 (9defd91b3)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
</details>

**Comment by SimonCropp** [comment]
gimme 15 min. i will exclude .vs

**Comment by SimonCropp** [comment]
try updating now

**Comment by distantcam** [comment]
Thanks for the quick turnaround!

I've updated and will report here if the issue comes back.
